DROP TABLE ALUNO;

CREATE TABLE ALUNO(
    RM NUMBER(10),
    NOME VARCHAR2(50),
    SOBRENOME VARCHAR2(50),
    V_CPF_ALUNO VARCHAR2(11),
    CONSTRAINT ALUNO_PK PRIMARY KEY (RM)
);

INSERT INTO ALUNO(RM, NOME, SOBRENOME, CPF) VALUES(1,'ANTONIO', 'ALVES', 1);
INSERT INTO ALUNO(RM, NOME, SOBRENOME, CPF) VALUES(2,'ARMANDO', 'ALVES', 2);
INSERT INTO ALUNO(RM, NOME, SOBRENOME, CPF) VALUES(3,'ROMARIO', 'ALVES', 3);

SELECT * FROM ALUNO;   

DELETE FROM ALUNO;

SET SERVEROUTPUT ON;



DECLARE 
//   V_NOME_ALUNO VARCHAR2(50);
//   V_SOBRENOME_ALUNO VARCHAR2(50);
//   V_CPF_ALUNO VARCHAR2(11);
   
    CURSOR C_ALUNO IS SELECT NOME, SOBRENOME, CPF FROM ALUNO;
          
BEGIN
// SELECT NOME INTO V_NOME_ALUNO FROM ALUNO WHERE RM =1;
// SELECT SOBRENOME INTO V_SOBRENOME_ALUNO FROM ALUNO WHERE RM = 1;
    FOR REG IN C_ALUUNO LOOP
    
    DBMS_OUTPUT.PUT_LINE('o nome aluno é: '||REG.NOME||' '||V_SOBRENOME_ALUNO);
    
    END LOOP;
END;
