DROP TABLE ALUNO;

SET SERVEROUTPUT ON

CREATE TABLE ALUNO(

    RA CHAR(9) NOT NULL,
    NOME VARCHAR (50) NOT NULL,
    CONSTRAINT ALUNO_PK PRIMARY KEY (RA)
);

INSERT INTO ALUNO (RA, NOME) VALUES ('1', 'Eduardo');
INSERT INTO ALUNO (RA, NOME) VALUES ('2', 'Lucca');
INSERT INTO ALUNO (RA, NOME) VALUES ('3', 'Gabi');


-- RA = V_RA  é a condição para a iniciação do SELECT, pois quando vc pesquisar o V_RA = 3, que no caso existe, o select será efetivado.
DECLARE 
    V_RA CHAR(9) := '3';
    V_NOME VARCHAR2(50);
BEGIN
    SELECT NOME INTO V_NOME FROM ALUNO WHERE RA = V_RA;
    DBMS_OUTPUT.PUT_LINE ('O nome do aluno é ' || V_NOME);
END;

DECLARE 
    V_RA CHAR(9) := '4';
    V_NOME VARCHAR2(50) := 'João';
BEGIN
    INSERT INTO ALUNO (RA, NOME) VALUES (V_RA, V_NOME);
END;

SELECT * FROM ALUNO;

DECLARE 
    V_RA CHAR(9) := '2';
    V_NOME VARCHAR2(50) := 'Gabriel';
BEGIN
    UPDATE ALUNO SET NOME = V_NOME WHERE RA= V_RA;
END;    

DROP TABLE BOLETIM;

CREATE TABLE BOLETIM(
    RM_ALUNO char(1),
    NM_DISC VARCHAR(50),
    NOTA_1 NUMBER(3,1),
    NOTA_2 NUMBER(3,1),
    NOTA_3 NUMBER(3,1),
    MEDIA NUMBER(3,1)
);

BEGIN
    INSERT INTO BOLETIM VALUES (1, 'PLSQL', 10, 7.5, 7.5, NULL);
    INSERT INTO BOLETIM VALUES (1, 'POO', 4.5, 10.0, 7.5, NULL);
    INSERT INTO BOLETIM VALUES (1, 'IA', 7.5, 6.5, 10.0, NULL);
    INSERT INTO BOLETIM VALUES (1, 'JAVA', 8.0, 2.5, 2.5, NULL);
end;
-- OU

BEGIN
    INSERT INTO BOLETIM VALUES (&RM, '&Disciplina1', &NOTA_1, &NOTA_2, &NOTA_3, NULL);
    INSERT INTO BOLETIM VALUES (&RM, '&Disciplina2', &NOTA_1, &NOTA_2, &NOTA_3, NULL);
    INSERT INTO BOLETIM VALUES (&RM, '&Disciplina3', &NOTA_1, &NOTA_2, &NOTA_3, NULL);
    INSERT INTO BOLETIM VALUES (&RM, '&Disciplina4', &NOTA_1, &NOTA_2, &NOTA_3, NULL);
END;

SELECT * FROM BOLETIM;

DECLARE 
    V_DISCIPLINA VARCHAR(20) := '&NOME_DISCIPLINA';
    V_CP1 NUMBER(3,1);
    V_CP2 V_CP1%TYPE;
    V_CP3 V_CP1%TYPE;
    V_MEDIA V_CP1%TYPE;
BEGIN
    SELECT NOTA_1,NOTA_2, NOTA_3 INTO V_CP1,V_CP2, V_CP3
        FROM BOLETIM WHERE NM_DISC = V_DISCIPLINA;
        V_MEDIA := (V_CP1 + V_CP2 + V_CP3) / 3;
    DBMS_OUTPUT.PUT_LINE(V_DISCIPLINA || ' - ' || v_cp1 || ' - ' || V_CP2 || ' - ' || V_CP3 || ' - ' || V_MEDIA);
    UPDATE BOLETIM SET MEDIA = V_MEDIA WHERE NM_DISC = V_DISCIPLINA;
END;


SET SERVEROUTPUT ON 
SET VERIFY OFF
